apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
spec:
  storageClassName: /root/.m2/repository
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi